import os
from conf.configSet_MountainCarContinuous.modelNetworkConfig import MODEL_NET_WORK_CONFIG_DICT_MOUNTAIN_CAR_CONTINUOUS

CONFIG_SET_MOUNTAIN_CAR_CONTINUOUS_CONFIG = os.path.dirname(os.path.realpath(__file__))