from log.expResult import EXP_RES as LOG_LIST

pendulum_dict = {
    "baseline": LOG_LIST + "/pendulumBaseline_0_6LogList.json",
    "baseline new reset": LOG_LIST + "/pendulumBaselineNewResetLogList.json",
    "baseline no dyna": LOG_LIST + "/pendulumBaselineNoDynaLogList.json",
    "baseline v3 0.4": LOG_LIST + "/pendulumBaselineV3_04_LogList.json",
    "baseline v3 0.5": LOG_LIST + "/pendulumBaselineV3_05_LogList.json",
    "baseline v3 0.6": LOG_LIST + "/pendulumBaselineV3_06_LogList.json",
    "baseline v3 0.7": LOG_LIST + "/pendulumBaselineV3_07_LogList.json",
    "baseline v3 0.8": LOG_LIST + "/pendulumBaselineV3_08_LogList.json",
    "baseline v5": LOG_LIST + '/pendulumBaselinev4_base_v4.json',
    "intel v1": LOG_LIST + "/pendulumIntelv1NewLogList.json",
    "intel v2": LOG_LIST + "/pendulumIntelv2NewLogList.json",
    # "random intel v1": LOG_LIST + "/pendulumRandomNewIntelv1LogList.json",
    # "intel v1 0.3": LOG_LIST + "/pendulumRandomIntelv1_0_3_LogList.json",
    # "intel v1 0.8": LOG_LIST + "/pendulumRandomIntelv1_0_8_LogList.json",
    # "intel v1 0.9": LOG_LIST + "/pendulumRandomIntelv1_0_9_LogList.json",
    # "intel v1 no reset": LOG_LIST + "/pendulumRandomIntelv1NoResetLogList.json",
    "intel v2.5": LOG_LIST + "/pendulumIntelv2_5NewLogList.json",
    "Reinforce 1": LOG_LIST + "/pendulumIntelv2RinforceStep_1_LogList.json",
    "Reinforce 5": LOG_LIST + "/pendulumIntelv2RinforceStep_5_LogList.json",
    "Reinforce 10": LOG_LIST + "/pendulumIntelv2RinforceStep_10_LogList.json",
    "Reinforce 20": LOG_LIST + "/pendulumIntelv2RinforceStep_20_LogList.json",
    "Reinforce 5_LR_001": LOG_LIST + "/pendulumIntelv2RinforceStep_5_LR_001_LogList.json",
    # "intel v1 pred reward": LOG_LIST + "/pendulumIntelv2PredRewardLogList.json",
    # "intel v1 split Action 5": LOG_LIST + "/pendulumIntelv1_Split_Action_5_LogList.json",
    "intel v2 split Action 5": LOG_LIST + "/pendulumIntelv2_Split_Action_5_LogList.json",
    "intel v2 split Action 5 reinforce step 1": LOG_LIST + "/pendulumIntelv2_Split_Action_5_REINFORCE_STE_1_LogList.json",
    # "assemble intel v2": LOG_LIST + '/pendulumv2_assemble_LogList.json',
    "direct reward": LOG_LIST + "/pendulumIntelv2_Direct_Reward_LogList.json",
    "intel v2 new step": LOG_LIST + '/pendulumIntelv2_new_step_LogList.json',
    # "intel v1 new step": LOG_LIST + '/pendulumIntelv1_new_step_LogList.json',
    "intel v2 new step reinforce 5": LOG_LIST + '/pendulumIntelv2RinforceStep_5_new_step_LogList.json',
    "intel v2 new step large memory": LOG_LIST + '/pendulumIntelv2_new_step_large_memory_LogList.json',
    "intel v2 new step split action": LOG_LIST + '/pendulumlntelv2_new_step_split_action_LogList.json',
    # "ensemble": LOG_LIST + "/pendulumIntelv2_ensemble_new_step_LogList.json",
    # "ensemble random sample": LOG_LIST + "/pendulumIntelv2_ensemble_new_step_random_sample_LogList.json",
    # "ensemble random sample only random": LOG_LIST + "/pendulumIntelv2_ensemble_new_step_random_sample_only_random_LogList.json",
    # "ensemble random sample no dyna": LOG_LIST + "/pendulumIntelv2_ensemble_new_step_random_sample_only_fix_LogList.json",
    "intel v3": LOG_LIST + "/pendulumIntelv3LogList.json",
    "intel v3 random": LOG_LIST + "/pendulumIntelv3_Random_LogList.json",
    "intel v3 10per": LOG_LIST + "/pendulumIntelv3_10Per_LogList.json",
    "intel v4": LOG_LIST + "/pendulumIntelv4LogList.json",
    "intel v4 10per": LOG_LIST + "/pendulumIntelv4_10Per_LogList.json",
    "intel v4 random": LOG_LIST + "/pendulumIntelv4_Random_LogList.json",
    "intel v5": LOG_LIST + '/pendulumIntelv5_intel_v4.json',

    'lyl NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT': LOG_LIST + '/pendulumIntelv5_LYL-NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT.json',
    'lyl NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT fix 1': LOG_LIST + '/pendulumIntelv5_LYL-NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT_FIX_1.json',
    'lyl NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT dqn 2': LOG_LIST + '/pendulumIntelv5_LYL-NC-5-ADAPT-COPY-INITPROB-05-REF-DISCOUNT-07_BestThre-08_2INT_DQN_2.json',
    'baseline v5 stepcount=12': LOG_LIST + '/pendulum_Baselinev5base_v5_stepcount=12.json',
    'Intelv5_random_fixednew_v5': LOG_LIST + '/Pendulum_Intelv5_random_fixednew_v5.json',

    'LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30': LOG_LIST + '/Pendulum_Intelv5_LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30.json',
    'LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30 fix 1': LOG_LIST + '/Pendulum_Intelv5_LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30_FIX_1.json',
    'LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30 dqn 2': LOG_LIST + '/Pendulum_Intelv5_LYL-NC-5-ADAPT-COPY-INITPROB-03-REF-DISCOUNT-07_BestThre-07_2INT_MSP08_MRL30_DQN_2.json',

    # 'intel_v5_action_split_5': LOG_LIST + '/Pendulum_Intel_v5_intel_v5_action_split_5.json',
    # 'intel_v5_REINFORCE_5': LOG_LIST + '/Pendulum_Intel_v5_intel_REINFORCE_5.json',
    # 'intel_v5_enlarge_trainer_memory': LOG_LIST + '/Pendulum_Intel_v5_intel_v5_enlarge_trainer_memory.json',

    'intel_v5_1_action_split_5': LOG_LIST + '/Pendulum_Intel_v5_1_intel_v5_1_action_split_5.json',
    'intel_v5_1_REINFORCE_5': LOG_LIST + '/Pendulum_Intel_v5_1_intel_v5_1_REINFORCE_5.json',
    'intel_v5_1_enlarge_trainer_memory': LOG_LIST + '/Pendulum_Intel_v5_1_intel_v5_1_enlarge_trainer_memory.json',
    'intel_v5_1_trainer_state_is_last_real_reward': LOG_LIST + '/Pendulum_Intel_v5_1_intel_v5_1_trainer_state_is_last_real_reward.json',
    'intel_v5_1_trainer_state_is_sample_count': LOG_LIST + '/Pendulum_Intel_v5_1_intel_v5_1_trainer_state_is_sample_count.json',

}
