import os
from conf.configSet_Pendulum_Intel_No_Dyna.modelNetworkConfig import MODEL_NET_WORK_CONFIG_DICT_PENDULUM_INTEL_NO_DYNA

CONFIG_SET_PENDULUM_INTEL_NO_DYNA = os.path.dirname(os.path.realpath(__file__))
